### ISSUE TITLE
exports fields not active

### ISSUE THREAD

**Issue by v1c3nt** [Kreyu/easyadmin-export-bundle#1]
all thanks for all the work done. I am having a problem it seems that my configuration of the fields is not taken into account.

it always returns me the field courses. which is a collection and therefore makes me a mistake

thank you
`
Teacher:
            class: App\Entity\Teacher
            list:
                   fields: ["id", "firstname", "lastname", "slug", "courses"]
            export:
                fields:
                    - { property: "id", label: "id" }
                    - { property: "firstname", label: "firstname" }
                    - { property: "lastname", label: "lastname" }
                    - { property: "slug", label: "slug" }
                label: 
                timestamp_format: d-m-Y
                metadata:
                    creator: "app.preIp.Iepg"
                    title: "list of teacher"
                    subject: "list of teacher"
                    description: "list of teacher"
                    category: "list"
                title: list of teacher
`

**Comment by Kreyu** [comment]
Hey, thanks for the information. I noticed some configuration nodes (including the fields) were not getting merged properly. I pushed a small fix, and I will keep an eye on this issue, but please note that this bundle is still in the development.

Thanks again, cheers

**Comment by Kreyu** [comment]
Closing because the inheritance issue has been fixed (changes made in #2). Please take a look at the new readme configuration part. Your entity configuration should like like following (the `label`, `timestamp_format` and `metadata` should be under the `export` node, not `fields`):

```yaml
Teacher: 
    class: App\Entity\Teacher 
    list: 
        fields: ["id", "firstname", "lastname", "slug", "courses"]
    export: 
        label: Export
        timestamp_format: d-m-Y 
        metadata: 
            creator: "app.preIp.Iepg" 
            title: "list of teacher" 
            subject: "list of teacher" 
            description: "list of teacher" 
            category: "list" 
        fields: 
            - { property: "id", label: "id" } 
            - { property: "firstname", label: "firstname" } 
            - { property: "lastname", label: "lastname" } 
            - { property: "slug", label: "slug" }
```

Cheers.
